//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.InfoSyncDefines;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import phoebe.eqx.smoi.wsdl.CommonComponents.SResultDescription;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sResult" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SResultDescription"/>
 *         &lt;element name="_balance" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="_activestop" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="_value" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="_valueadd" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="_validity" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="_validityadd" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sResult",
    "balance",
    "activestop",
    "value",
    "valueadd",
    "validity",
    "validityadd"
})
@XmlRootElement(name = "do_ETopupResponse", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
public class DoETopupResponse {

    @XmlElement(namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", required = true)
    protected SResultDescription sResult;
    @XmlElement(name = "_balance", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected long balance;
    @XmlElement(name = "_activestop", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar activestop;
    @XmlElement(name = "_value", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected long value;
    @XmlElement(name = "_valueadd", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected Long valueadd;
    @XmlElement(name = "_validity", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validity;
    @XmlElement(name = "_validityadd", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected long validityadd;

    /**
     * Gets the value of the sResult property.
     * 
     * @return
     *     possible object is
     *     {@link SResultDescription }
     *     
     */
    public SResultDescription getSResult() {
        return sResult;
    }

    /**
     * Sets the value of the sResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SResultDescription }
     *     
     */
    public void setSResult(SResultDescription value) {
        this.sResult = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     */
    public long getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     */
    public void setBalance(long value) {
        this.balance = value;
    }

    /**
     * Gets the value of the activestop property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActivestop() {
        return activestop;
    }

    /**
     * Sets the value of the activestop property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActivestop(XMLGregorianCalendar value) {
        this.activestop = value;
    }

    /**
     * Gets the value of the value property.
     * 
     */
    public long getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(long value) {
        this.value = value;
    }

    /**
     * Gets the value of the valueadd property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getValueadd() {
        return valueadd;
    }

    /**
     * Sets the value of the valueadd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setValueadd(Long value) {
        this.valueadd = value;
    }

    /**
     * Gets the value of the validity property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidity() {
        return validity;
    }

    /**
     * Sets the value of the validity property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidity(XMLGregorianCalendar value) {
        this.validity = value;
    }

    /**
     * Gets the value of the validityadd property.
     * 
     */
    public long getValidityadd() {
        return validityadd;
    }

    /**
     * Sets the value of the validityadd property.
     * 
     */
    public void setValidityadd(long value) {
        this.validityadd = value;
    }

}
