//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.InfoSyncDefines;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import phoebe.eqx.smoi.wsdl.CommonComponents.FreeResourceList;
import phoebe.eqx.smoi.wsdl.CommonComponents.SBalanceList;
import phoebe.eqx.smoi.wsdl.CommonComponents.SProductOrderResultList;


/**
 * <p>Java class for DoProductReward complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DoProductReward">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WorkOrderType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="_transaction_id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="32"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_cust_id" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="32"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_acct_id" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_user_id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="_phone_id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BalanceList" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SBalanceList" minOccurs="0"/>
 *         &lt;element name="ProductOrderResultList" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SProductOrderResultList" minOccurs="0"/>
 *         &lt;element name="FreeResourceList" type="{http://www.asiainfo.com/obd/CommonComponents.obd}FreeResourceList" minOccurs="0"/>
 *         &lt;element name="_reason_code" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="_countBalanceRec" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="_countFreeResourceRec" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="_countProductRec" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="OperateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="TotalBalanceList" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SBalanceList" minOccurs="0"/>
 *         &lt;element name="TotalProductOrderResultList" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SProductOrderResultList" minOccurs="0"/>
 *         &lt;element name="TotalFreeResourceList" type="{http://www.asiainfo.com/obd/CommonComponents.obd}FreeResourceList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoProductReward", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", propOrder = {
    "workOrderType",
    "transactionId",
    "custId",
    "acctId",
    "userId",
    "phoneId",
    "balanceList",
    "productOrderResultList",
    "freeResourceList",
    "reasonCode",
    "countBalanceRec",
    "countFreeResourceRec",
    "countProductRec",
    "operateTime",
    "totalBalanceList",
    "totalProductOrderResultList",
    "totalFreeResourceList"
})
public class DoProductReward2 {

    @XmlElement(name = "WorkOrderType", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected int workOrderType;
    @XmlElement(name = "_transaction_id", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", required = true)
    protected String transactionId;
    @XmlElement(name = "_cust_id", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected String custId;
    @XmlElement(name = "_acct_id", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected String acctId;
    @XmlElement(name = "_user_id", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected Long userId;
    @XmlElement(name = "_phone_id", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", required = true)
    protected String phoneId;
    @XmlElement(name = "BalanceList", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected SBalanceList balanceList;
    @XmlElement(name = "ProductOrderResultList", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected SProductOrderResultList productOrderResultList;
    @XmlElement(name = "FreeResourceList", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected FreeResourceList freeResourceList;
    @XmlElement(name = "_reason_code", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected Short reasonCode;
    @XmlElement(name = "_countBalanceRec", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected Long countBalanceRec;
    @XmlElement(name = "_countFreeResourceRec", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected Long countFreeResourceRec;
    @XmlElement(name = "_countProductRec", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected Long countProductRec;
    @XmlElement(name = "OperateTime", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar operateTime;
    @XmlElement(name = "TotalBalanceList", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected SBalanceList totalBalanceList;
    @XmlElement(name = "TotalProductOrderResultList", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected SProductOrderResultList totalProductOrderResultList;
    @XmlElement(name = "TotalFreeResourceList", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected FreeResourceList totalFreeResourceList;

    /**
     * Gets the value of the workOrderType property.
     * 
     */
    public int getWorkOrderType() {
        return workOrderType;
    }

    /**
     * Sets the value of the workOrderType property.
     * 
     */
    public void setWorkOrderType(int value) {
        this.workOrderType = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the custId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustId() {
        return custId;
    }

    /**
     * Sets the value of the custId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustId(String value) {
        this.custId = value;
    }

    /**
     * Gets the value of the acctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctId() {
        return acctId;
    }

    /**
     * Sets the value of the acctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctId(String value) {
        this.acctId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUserId(Long value) {
        this.userId = value;
    }

    /**
     * Gets the value of the phoneId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneId() {
        return phoneId;
    }

    /**
     * Sets the value of the phoneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneId(String value) {
        this.phoneId = value;
    }

    /**
     * Gets the value of the balanceList property.
     * 
     * @return
     *     possible object is
     *     {@link SBalanceList }
     *     
     */
    public SBalanceList getBalanceList() {
        return balanceList;
    }

    /**
     * Sets the value of the balanceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SBalanceList }
     *     
     */
    public void setBalanceList(SBalanceList value) {
        this.balanceList = value;
    }

    /**
     * Gets the value of the productOrderResultList property.
     * 
     * @return
     *     possible object is
     *     {@link SProductOrderResultList }
     *     
     */
    public SProductOrderResultList getProductOrderResultList() {
        return productOrderResultList;
    }

    /**
     * Sets the value of the productOrderResultList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SProductOrderResultList }
     *     
     */
    public void setProductOrderResultList(SProductOrderResultList value) {
        this.productOrderResultList = value;
    }

    /**
     * Gets the value of the freeResourceList property.
     * 
     * @return
     *     possible object is
     *     {@link FreeResourceList }
     *     
     */
    public FreeResourceList getFreeResourceList() {
        return freeResourceList;
    }

    /**
     * Sets the value of the freeResourceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeResourceList }
     *     
     */
    public void setFreeResourceList(FreeResourceList value) {
        this.freeResourceList = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setReasonCode(Short value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the countBalanceRec property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCountBalanceRec() {
        return countBalanceRec;
    }

    /**
     * Sets the value of the countBalanceRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCountBalanceRec(Long value) {
        this.countBalanceRec = value;
    }

    /**
     * Gets the value of the countFreeResourceRec property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCountFreeResourceRec() {
        return countFreeResourceRec;
    }

    /**
     * Sets the value of the countFreeResourceRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCountFreeResourceRec(Long value) {
        this.countFreeResourceRec = value;
    }

    /**
     * Gets the value of the countProductRec property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCountProductRec() {
        return countProductRec;
    }

    /**
     * Sets the value of the countProductRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCountProductRec(Long value) {
        this.countProductRec = value;
    }

    /**
     * Gets the value of the operateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOperateTime() {
        return operateTime;
    }

    /**
     * Sets the value of the operateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOperateTime(XMLGregorianCalendar value) {
        this.operateTime = value;
    }

    /**
     * Gets the value of the totalBalanceList property.
     * 
     * @return
     *     possible object is
     *     {@link SBalanceList }
     *     
     */
    public SBalanceList getTotalBalanceList() {
        return totalBalanceList;
    }

    /**
     * Sets the value of the totalBalanceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SBalanceList }
     *     
     */
    public void setTotalBalanceList(SBalanceList value) {
        this.totalBalanceList = value;
    }

    /**
     * Gets the value of the totalProductOrderResultList property.
     * 
     * @return
     *     possible object is
     *     {@link SProductOrderResultList }
     *     
     */
    public SProductOrderResultList getTotalProductOrderResultList() {
        return totalProductOrderResultList;
    }

    /**
     * Sets the value of the totalProductOrderResultList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SProductOrderResultList }
     *     
     */
    public void setTotalProductOrderResultList(SProductOrderResultList value) {
        this.totalProductOrderResultList = value;
    }

    /**
     * Gets the value of the totalFreeResourceList property.
     * 
     * @return
     *     possible object is
     *     {@link FreeResourceList }
     *     
     */
    public FreeResourceList getTotalFreeResourceList() {
        return totalFreeResourceList;
    }

    /**
     * Sets the value of the totalFreeResourceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeResourceList }
     *     
     */
    public void setTotalFreeResourceList(FreeResourceList value) {
        this.totalFreeResourceList = value;
    }

}
