//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.InfoSyncDefines;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import phoebe.eqx.smoi.wsdl.CommonComponents.SOperInfo;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sOper" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SOperInfo"/>
 *         &lt;element name="_query_type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CAList" type="{http://www.asiainfo.com/obd/InfoSyncDefines.obd}CAList" minOccurs="0"/>
 *         &lt;element name="BAList" type="{http://www.asiainfo.com/obd/InfoSyncDefines.obd}BAList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sOper",
    "queryType",
    "caList",
    "baList"
})
@XmlRootElement(name = "do_QueryCorporate", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
public class DoQueryCorporate {

    @XmlElement(namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", required = true)
    protected SOperInfo sOper;
    @XmlElement(name = "_query_type", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected short queryType;
    @XmlElement(name = "CAList", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected CAList caList;
    @XmlElement(name = "BAList", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected BAList baList;

    /**
     * Gets the value of the sOper property.
     * 
     * @return
     *     possible object is
     *     {@link SOperInfo }
     *     
     */
    public SOperInfo getSOper() {
        return sOper;
    }

    /**
     * Sets the value of the sOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOperInfo }
     *     
     */
    public void setSOper(SOperInfo value) {
        this.sOper = value;
    }

    /**
     * Gets the value of the queryType property.
     * 
     */
    public short getQueryType() {
        return queryType;
    }

    /**
     * Sets the value of the queryType property.
     * 
     */
    public void setQueryType(short value) {
        this.queryType = value;
    }

    /**
     * Gets the value of the caList property.
     * 
     * @return
     *     possible object is
     *     {@link CAList }
     *     
     */
    public CAList getCAList() {
        return caList;
    }

    /**
     * Sets the value of the caList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAList }
     *     
     */
    public void setCAList(CAList value) {
        this.caList = value;
    }

    /**
     * Gets the value of the baList property.
     * 
     * @return
     *     possible object is
     *     {@link BAList }
     *     
     */
    public BAList getBAList() {
        return baList;
    }

    /**
     * Sets the value of the baList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAList }
     *     
     */
    public void setBAList(BAList value) {
        this.baList = value;
    }

}
