//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.InfoSyncDefines;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StateChangeReq" type="{http://www.asiainfo.com/obd/InfoSyncDefines.obd}DoStateChange"/>
 *         &lt;element name="_send_to" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stateChangeReq",
    "sendTo"
})
@XmlRootElement(name = "do_StateChange", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
public class DoStateChange {

    @XmlElement(name = "StateChangeReq", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", required = true)
    protected DoStateChange2 stateChangeReq;
    @XmlElement(name = "_send_to", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected Short sendTo;

    /**
     * Gets the value of the stateChangeReq property.
     * 
     * @return
     *     possible object is
     *     {@link DoStateChange2 }
     *     
     */
    public DoStateChange2 getStateChangeReq() {
        return stateChangeReq;
    }

    /**
     * Sets the value of the stateChangeReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoStateChange2 }
     *     
     */
    public void setStateChangeReq(DoStateChange2 value) {
        this.stateChangeReq = value;
    }

    /**
     * Gets the value of the sendTo property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSendTo() {
        return sendTo;
    }

    /**
     * Sets the value of the sendTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSendTo(Short value) {
        this.sendTo = value;
    }

}
