//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.InfoSyncDefines;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FreeResourceGroupRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FreeResourceGroupRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_free_resource_group" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FreeResourceRecordList" type="{http://www.asiainfo.com/obd/InfoSyncDefines.obd}FreeResourceRecordList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FreeResourceGroupRecord", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", propOrder = {
    "freeResourceGroup",
    "freeResourceRecordList"
})
public class FreeResourceGroupRecord {

    @XmlElement(name = "_free_resource_group", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected String freeResourceGroup;
    @XmlElement(name = "FreeResourceRecordList", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected FreeResourceRecordList freeResourceRecordList;

    /**
     * Gets the value of the freeResourceGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeResourceGroup() {
        return freeResourceGroup;
    }

    /**
     * Sets the value of the freeResourceGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeResourceGroup(String value) {
        this.freeResourceGroup = value;
    }

    /**
     * Gets the value of the freeResourceRecordList property.
     * 
     * @return
     *     possible object is
     *     {@link FreeResourceRecordList }
     *     
     */
    public FreeResourceRecordList getFreeResourceRecordList() {
        return freeResourceRecordList;
    }

    /**
     * Sets the value of the freeResourceRecordList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeResourceRecordList }
     *     
     */
    public void setFreeResourceRecordList(FreeResourceRecordList value) {
        this.freeResourceRecordList = value;
    }

}
