//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.InfoSyncDefines;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HighestTransactionGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HighestTransactionGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DestinationNumberList" type="{http://www.asiainfo.com/obd/InfoSyncDefines.obd}DestinationNumberList" minOccurs="0"/>
 *         &lt;element name="_times" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HighestTransactionGroup", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", propOrder = {
    "destinationNumberList",
    "times"
})
public class HighestTransactionGroup {

    @XmlElement(name = "DestinationNumberList", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected DestinationNumberList destinationNumberList;
    @XmlElement(name = "_times", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected Long times;

    /**
     * Gets the value of the destinationNumberList property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationNumberList }
     *     
     */
    public DestinationNumberList getDestinationNumberList() {
        return destinationNumberList;
    }

    /**
     * Sets the value of the destinationNumberList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationNumberList }
     *     
     */
    public void setDestinationNumberList(DestinationNumberList value) {
        this.destinationNumberList = value;
    }

    /**
     * Gets the value of the times property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimes() {
        return times;
    }

    /**
     * Sets the value of the times property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimes(Long value) {
        this.times = value;
    }

}
