//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.InfoSyncDefines;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import phoebe.eqx.smoi.wsdl.CommonComponents.SAccount;
import phoebe.eqx.smoi.wsdl.CommonComponents.SBalanceList;
import phoebe.eqx.smoi.wsdl.CommonComponents.SCustomer;
import phoebe.eqx.smoi.wsdl.CommonComponents.SUser;


/**
 * <p>Java class for UserInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_user_info" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SUser" minOccurs="0"/>
 *         &lt;element name="_cust_info" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SCustomer" minOccurs="0"/>
 *         &lt;element name="_acct_info" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SAccount" minOccurs="0"/>
 *         &lt;element name="_balance_info" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SBalanceList" minOccurs="0"/>
 *         &lt;element name="_remain_info" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserInformation", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd", propOrder = {
    "userInfo",
    "custInfo",
    "acctInfo",
    "balanceInfo",
    "remainInfo"
})
public class UserInformation {

    @XmlElement(name = "_user_info", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected SUser userInfo;
    @XmlElement(name = "_cust_info", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected SCustomer custInfo;
    @XmlElement(name = "_acct_info", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected SAccount acctInfo;
    @XmlElement(name = "_balance_info", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected SBalanceList balanceInfo;
    @XmlElement(name = "_remain_info", namespace = "http://www.asiainfo.com/obd/InfoSyncDefines.obd")
    protected Object remainInfo;

    /**
     * Gets the value of the userInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SUser }
     *     
     */
    public SUser getUserInfo() {
        return userInfo;
    }

    /**
     * Sets the value of the userInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SUser }
     *     
     */
    public void setUserInfo(SUser value) {
        this.userInfo = value;
    }

    /**
     * Gets the value of the custInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SCustomer }
     *     
     */
    public SCustomer getCustInfo() {
        return custInfo;
    }

    /**
     * Sets the value of the custInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCustomer }
     *     
     */
    public void setCustInfo(SCustomer value) {
        this.custInfo = value;
    }

    /**
     * Gets the value of the acctInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SAccount }
     *     
     */
    public SAccount getAcctInfo() {
        return acctInfo;
    }

    /**
     * Sets the value of the acctInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAccount }
     *     
     */
    public void setAcctInfo(SAccount value) {
        this.acctInfo = value;
    }

    /**
     * Gets the value of the balanceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SBalanceList }
     *     
     */
    public SBalanceList getBalanceInfo() {
        return balanceInfo;
    }

    /**
     * Sets the value of the balanceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SBalanceList }
     *     
     */
    public void setBalanceInfo(SBalanceList value) {
        this.balanceInfo = value;
    }

    /**
     * Gets the value of the remainInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRemainInfo() {
        return remainInfo;
    }

    /**
     * Sets the value of the remainInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRemainInfo(Object value) {
        this.remainInfo = value;
    }

}
