//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.CommonComponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdTransferParam complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdTransferParam">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_org_acct_id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_org_phone_id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_asset_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="targetTransDetailList" type="{http://www.asiainfo.com/obd/CommonComponents.obd}TransferDetailList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdTransferParam", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd", propOrder = {
    "orgAcctId",
    "orgPhoneId",
    "assetId",
    "targetTransDetailList"
})
public class AdTransferParam {

    @XmlElement(name = "_org_acct_id", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd", required = true)
    protected String orgAcctId;
    @XmlElement(name = "_org_phone_id", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd", required = true)
    protected String orgPhoneId;
    @XmlElement(name = "_asset_id", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected long assetId;
    @XmlElement(namespace = "http://www.asiainfo.com/obd/CommonComponents.obd", required = true)
    protected TransferDetailList targetTransDetailList;

    /**
     * Gets the value of the orgAcctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgAcctId() {
        return orgAcctId;
    }

    /**
     * Sets the value of the orgAcctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgAcctId(String value) {
        this.orgAcctId = value;
    }

    /**
     * Gets the value of the orgPhoneId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgPhoneId() {
        return orgPhoneId;
    }

    /**
     * Sets the value of the orgPhoneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgPhoneId(String value) {
        this.orgPhoneId = value;
    }

    /**
     * Gets the value of the assetId property.
     * 
     */
    public long getAssetId() {
        return assetId;
    }

    /**
     * Sets the value of the assetId property.
     * 
     */
    public void setAssetId(long value) {
        this.assetId = value;
    }

    /**
     * Gets the value of the targetTransDetailList property.
     * 
     * @return
     *     possible object is
     *     {@link TransferDetailList }
     *     
     */
    public TransferDetailList getTargetTransDetailList() {
        return targetTransDetailList;
    }

    /**
     * Sets the value of the targetTransDetailList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferDetailList }
     *     
     */
    public void setTargetTransDetailList(TransferDetailList value) {
        this.targetTransDetailList = value;
    }

}
