//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.CommonComponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ByUsageCondition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ByUsageCondition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_network_type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_distance_type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_vpn_call_type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_seg_type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_roaming_network" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *               &lt;enumeration value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ByUsageCondition", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd", propOrder = {
    "networkType",
    "distanceType",
    "vpnCallType",
    "segType",
    "roamingNetwork"
})
public class ByUsageCondition {

    @XmlElement(name = "_network_type", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected Short networkType;
    @XmlElement(name = "_distance_type", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected Short distanceType;
    @XmlElement(name = "_vpn_call_type", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected Short vpnCallType;
    @XmlElement(name = "_seg_type", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected Short segType;
    @XmlElement(name = "_roaming_network", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected Short roamingNetwork;

    /**
     * Gets the value of the networkType property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNetworkType() {
        return networkType;
    }

    /**
     * Sets the value of the networkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNetworkType(Short value) {
        this.networkType = value;
    }

    /**
     * Gets the value of the distanceType property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDistanceType() {
        return distanceType;
    }

    /**
     * Sets the value of the distanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDistanceType(Short value) {
        this.distanceType = value;
    }

    /**
     * Gets the value of the vpnCallType property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getVpnCallType() {
        return vpnCallType;
    }

    /**
     * Sets the value of the vpnCallType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setVpnCallType(Short value) {
        this.vpnCallType = value;
    }

    /**
     * Gets the value of the segType property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSegType() {
        return segType;
    }

    /**
     * Sets the value of the segType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSegType(Short value) {
        this.segType = value;
    }

    /**
     * Gets the value of the roamingNetwork property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getRoamingNetwork() {
        return roamingNetwork;
    }

    /**
     * Sets the value of the roamingNetwork property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setRoamingNetwork(Short value) {
        this.roamingNetwork = value;
    }

}
