//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.CommonComponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CDRData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CDRData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_phone_id" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GroupingDomesticList" type="{http://www.asiainfo.com/obd/CommonComponents.obd}GroupingCDRHeaderList" minOccurs="0"/>
 *         &lt;element name="GroupingIRList" type="{http://www.asiainfo.com/obd/CommonComponents.obd}GroupingCDRHeaderList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CDRData", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd", propOrder = {
    "phoneId",
    "groupingDomesticList",
    "groupingIRList"
})
public class CDRData {

    @XmlElement(name = "_phone_id", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String phoneId;
    @XmlElement(name = "GroupingDomesticList", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected GroupingCDRHeaderList groupingDomesticList;
    @XmlElement(name = "GroupingIRList", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected GroupingCDRHeaderList groupingIRList;

    /**
     * Gets the value of the phoneId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneId() {
        return phoneId;
    }

    /**
     * Sets the value of the phoneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneId(String value) {
        this.phoneId = value;
    }

    /**
     * Gets the value of the groupingDomesticList property.
     * 
     * @return
     *     possible object is
     *     {@link GroupingCDRHeaderList }
     *     
     */
    public GroupingCDRHeaderList getGroupingDomesticList() {
        return groupingDomesticList;
    }

    /**
     * Sets the value of the groupingDomesticList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupingCDRHeaderList }
     *     
     */
    public void setGroupingDomesticList(GroupingCDRHeaderList value) {
        this.groupingDomesticList = value;
    }

    /**
     * Gets the value of the groupingIRList property.
     * 
     * @return
     *     possible object is
     *     {@link GroupingCDRHeaderList }
     *     
     */
    public GroupingCDRHeaderList getGroupingIRList() {
        return groupingIRList;
    }

    /**
     * Sets the value of the groupingIRList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupingCDRHeaderList }
     *     
     */
    public void setGroupingIRList(GroupingCDRHeaderList value) {
        this.groupingIRList = value;
    }

}
