//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.CommonComponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CustomerBasicInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerBasicInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SContactOperList" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SContactOperList" minOccurs="0"/>
 *         &lt;element name="_cust_id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_cust_type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_sub_cust_type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_cust_title" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_family_name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="128"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_first_name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="128"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_cust_segment" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_birthday" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="_gender" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_reg_name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="128"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_reg_type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_reg_nbr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_issue_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="_language" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_taxexemptref" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_custBMcalldetail" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_custBMsummary" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_emailcustBMcall" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_emailcustBMsummary" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_attrcustemail" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_hierarchybillingflag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sBillCycle" type="{http://www.asiainfo.com/obd/CommonComponents.obd}SBillCycle" minOccurs="0"/>
 *         &lt;element name="_vat_name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_fax_cust_bm_call" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_fax_cust_bm_sum" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_billhandlingcode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerBasicInfo", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd", propOrder = {
    "sContactOperList",
    "custId",
    "custType",
    "subCustType",
    "custTitle",
    "familyName",
    "firstName",
    "custSegment",
    "birthday",
    "gender",
    "regName",
    "regType",
    "regNbr",
    "issueDate",
    "language",
    "taxexemptref",
    "custBMcalldetail",
    "custBMsummary",
    "emailcustBMcall",
    "emailcustBMsummary",
    "attrcustemail",
    "hierarchybillingflag",
    "sBillCycle",
    "vatName",
    "faxCustBmCall",
    "faxCustBmSum",
    "billhandlingcode"
})
public class CustomerBasicInfo {

    @XmlElement(name = "SContactOperList", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected SContactOperList sContactOperList;
    @XmlElement(name = "_cust_id", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd", required = true)
    protected String custId;
    @XmlElement(name = "_cust_type", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String custType;
    @XmlElement(name = "_sub_cust_type", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String subCustType;
    @XmlElement(name = "_cust_title", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String custTitle;
    @XmlElement(name = "_family_name", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String familyName;
    @XmlElement(name = "_first_name", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String firstName;
    @XmlElement(name = "_cust_segment", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String custSegment;
    @XmlElement(name = "_birthday", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar birthday;
    @XmlElement(name = "_gender", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String gender;
    @XmlElement(name = "_reg_name", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String regName;
    @XmlElement(name = "_reg_type", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String regType;
    @XmlElement(name = "_reg_nbr", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String regNbr;
    @XmlElement(name = "_issue_date", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar issueDate;
    @XmlElement(name = "_language", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String language;
    @XmlElement(name = "_taxexemptref", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String taxexemptref;
    @XmlElement(name = "_custBMcalldetail", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String custBMcalldetail;
    @XmlElement(name = "_custBMsummary", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String custBMsummary;
    @XmlElement(name = "_emailcustBMcall", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String emailcustBMcall;
    @XmlElement(name = "_emailcustBMsummary", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String emailcustBMsummary;
    @XmlElement(name = "_attrcustemail", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String attrcustemail;
    @XmlElement(name = "_hierarchybillingflag", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String hierarchybillingflag;
    @XmlElement(namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected SBillCycle sBillCycle;
    @XmlElement(name = "_vat_name", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String vatName;
    @XmlElement(name = "_fax_cust_bm_call", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String faxCustBmCall;
    @XmlElement(name = "_fax_cust_bm_sum", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String faxCustBmSum;
    @XmlElement(name = "_billhandlingcode", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String billhandlingcode;

    /**
     * Gets the value of the sContactOperList property.
     * 
     * @return
     *     possible object is
     *     {@link SContactOperList }
     *     
     */
    public SContactOperList getSContactOperList() {
        return sContactOperList;
    }

    /**
     * Sets the value of the sContactOperList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SContactOperList }
     *     
     */
    public void setSContactOperList(SContactOperList value) {
        this.sContactOperList = value;
    }

    /**
     * Gets the value of the custId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustId() {
        return custId;
    }

    /**
     * Sets the value of the custId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustId(String value) {
        this.custId = value;
    }

    /**
     * Gets the value of the custType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustType() {
        return custType;
    }

    /**
     * Sets the value of the custType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustType(String value) {
        this.custType = value;
    }

    /**
     * Gets the value of the subCustType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCustType() {
        return subCustType;
    }

    /**
     * Sets the value of the subCustType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCustType(String value) {
        this.subCustType = value;
    }

    /**
     * Gets the value of the custTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustTitle() {
        return custTitle;
    }

    /**
     * Sets the value of the custTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustTitle(String value) {
        this.custTitle = value;
    }

    /**
     * Gets the value of the familyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * Sets the value of the familyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyName(String value) {
        this.familyName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the custSegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustSegment() {
        return custSegment;
    }

    /**
     * Sets the value of the custSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustSegment(String value) {
        this.custSegment = value;
    }

    /**
     * Gets the value of the birthday property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthday() {
        return birthday;
    }

    /**
     * Sets the value of the birthday property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthday(XMLGregorianCalendar value) {
        this.birthday = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the regName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegName() {
        return regName;
    }

    /**
     * Sets the value of the regName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegName(String value) {
        this.regName = value;
    }

    /**
     * Gets the value of the regType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegType() {
        return regType;
    }

    /**
     * Sets the value of the regType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegType(String value) {
        this.regType = value;
    }

    /**
     * Gets the value of the regNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegNbr() {
        return regNbr;
    }

    /**
     * Sets the value of the regNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegNbr(String value) {
        this.regNbr = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDate(XMLGregorianCalendar value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the taxexemptref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxexemptref() {
        return taxexemptref;
    }

    /**
     * Sets the value of the taxexemptref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxexemptref(String value) {
        this.taxexemptref = value;
    }

    /**
     * Gets the value of the custBMcalldetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustBMcalldetail() {
        return custBMcalldetail;
    }

    /**
     * Sets the value of the custBMcalldetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustBMcalldetail(String value) {
        this.custBMcalldetail = value;
    }

    /**
     * Gets the value of the custBMsummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustBMsummary() {
        return custBMsummary;
    }

    /**
     * Sets the value of the custBMsummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustBMsummary(String value) {
        this.custBMsummary = value;
    }

    /**
     * Gets the value of the emailcustBMcall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailcustBMcall() {
        return emailcustBMcall;
    }

    /**
     * Sets the value of the emailcustBMcall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailcustBMcall(String value) {
        this.emailcustBMcall = value;
    }

    /**
     * Gets the value of the emailcustBMsummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailcustBMsummary() {
        return emailcustBMsummary;
    }

    /**
     * Sets the value of the emailcustBMsummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailcustBMsummary(String value) {
        this.emailcustBMsummary = value;
    }

    /**
     * Gets the value of the attrcustemail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttrcustemail() {
        return attrcustemail;
    }

    /**
     * Sets the value of the attrcustemail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttrcustemail(String value) {
        this.attrcustemail = value;
    }

    /**
     * Gets the value of the hierarchybillingflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHierarchybillingflag() {
        return hierarchybillingflag;
    }

    /**
     * Sets the value of the hierarchybillingflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHierarchybillingflag(String value) {
        this.hierarchybillingflag = value;
    }

    /**
     * Gets the value of the sBillCycle property.
     * 
     * @return
     *     possible object is
     *     {@link SBillCycle }
     *     
     */
    public SBillCycle getSBillCycle() {
        return sBillCycle;
    }

    /**
     * Sets the value of the sBillCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link SBillCycle }
     *     
     */
    public void setSBillCycle(SBillCycle value) {
        this.sBillCycle = value;
    }

    /**
     * Gets the value of the vatName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatName() {
        return vatName;
    }

    /**
     * Sets the value of the vatName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatName(String value) {
        this.vatName = value;
    }

    /**
     * Gets the value of the faxCustBmCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxCustBmCall() {
        return faxCustBmCall;
    }

    /**
     * Sets the value of the faxCustBmCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxCustBmCall(String value) {
        this.faxCustBmCall = value;
    }

    /**
     * Gets the value of the faxCustBmSum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxCustBmSum() {
        return faxCustBmSum;
    }

    /**
     * Sets the value of the faxCustBmSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxCustBmSum(String value) {
        this.faxCustBmSum = value;
    }

    /**
     * Gets the value of the billhandlingcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillhandlingcode() {
        return billhandlingcode;
    }

    /**
     * Sets the value of the billhandlingcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillhandlingcode(String value) {
        this.billhandlingcode = value;
    }

}
