//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.CommonComponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SCredit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SCredit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_busi_service_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="_unlimited_flag" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="_credit" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="_remain_credit" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="_temp_credit" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="_advance_payment" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="_usage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="_unpaid_payment" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SCredit", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd", propOrder = {
    "busiServiceId",
    "unlimitedFlag",
    "credit",
    "remainCredit",
    "tempCredit",
    "advancePayment",
    "usage",
    "unpaidPayment"
})
public class SCredit {

    @XmlElement(name = "_busi_service_id", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected long busiServiceId;
    @XmlElement(name = "_unlimited_flag", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected short unlimitedFlag;
    @XmlElement(name = "_credit", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected double credit;
    @XmlElement(name = "_remain_credit", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected Long remainCredit;
    @XmlElement(name = "_temp_credit", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected Long tempCredit;
    @XmlElement(name = "_advance_payment", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected Long advancePayment;
    @XmlElement(name = "_usage", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String usage;
    @XmlElement(name = "_unpaid_payment", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected Long unpaidPayment;

    /**
     * Gets the value of the busiServiceId property.
     * 
     */
    public long getBusiServiceId() {
        return busiServiceId;
    }

    /**
     * Sets the value of the busiServiceId property.
     * 
     */
    public void setBusiServiceId(long value) {
        this.busiServiceId = value;
    }

    /**
     * Gets the value of the unlimitedFlag property.
     * 
     */
    public short getUnlimitedFlag() {
        return unlimitedFlag;
    }

    /**
     * Sets the value of the unlimitedFlag property.
     * 
     */
    public void setUnlimitedFlag(short value) {
        this.unlimitedFlag = value;
    }

    /**
     * Gets the value of the credit property.
     * 
     */
    public double getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     * 
     */
    public void setCredit(double value) {
        this.credit = value;
    }

    /**
     * Gets the value of the remainCredit property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRemainCredit() {
        return remainCredit;
    }

    /**
     * Sets the value of the remainCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRemainCredit(Long value) {
        this.remainCredit = value;
    }

    /**
     * Gets the value of the tempCredit property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTempCredit() {
        return tempCredit;
    }

    /**
     * Sets the value of the tempCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTempCredit(Long value) {
        this.tempCredit = value;
    }

    /**
     * Gets the value of the advancePayment property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAdvancePayment() {
        return advancePayment;
    }

    /**
     * Sets the value of the advancePayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAdvancePayment(Long value) {
        this.advancePayment = value;
    }

    /**
     * Gets the value of the usage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsage(String value) {
        this.usage = value;
    }

    /**
     * Gets the value of the unpaidPayment property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUnpaidPayment() {
        return unpaidPayment;
    }

    /**
     * Sets the value of the unpaidPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUnpaidPayment(Long value) {
        this.unpaidPayment = value;
    }

}
