//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.01 at 04:26:27 PM ICT 
//


package phoebe.eqx.smoi.wsdl.CommonComponents;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SMultiCommunityGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SMultiCommunityGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_group_id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_group_type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="32"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_group_name_thai" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_group_name_eng" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_same_group" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_phone_id_A" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="_phone_id_B" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SMultiCommunityGroup", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd", propOrder = {
    "groupId",
    "groupType",
    "groupNameThai",
    "groupNameEng",
    "sameGroup",
    "phoneIdA",
    "phoneIdB"
})
public class SMultiCommunityGroup {

    @XmlElement(name = "_group_id", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd", required = true)
    protected String groupId;
    @XmlElement(name = "_group_type", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String groupType;
    @XmlElement(name = "_group_name_thai", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String groupNameThai;
    @XmlElement(name = "_group_name_eng", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String groupNameEng;
    @XmlElement(name = "_same_group", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String sameGroup;
    @XmlElement(name = "_phone_id_A", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String phoneIdA;
    @XmlElement(name = "_phone_id_B", namespace = "http://www.asiainfo.com/obd/CommonComponents.obd")
    protected String phoneIdB;

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the groupType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupType() {
        return groupType;
    }

    /**
     * Sets the value of the groupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupType(String value) {
        this.groupType = value;
    }

    /**
     * Gets the value of the groupNameThai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupNameThai() {
        return groupNameThai;
    }

    /**
     * Sets the value of the groupNameThai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupNameThai(String value) {
        this.groupNameThai = value;
    }

    /**
     * Gets the value of the groupNameEng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupNameEng() {
        return groupNameEng;
    }

    /**
     * Sets the value of the groupNameEng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupNameEng(String value) {
        this.groupNameEng = value;
    }

    /**
     * Gets the value of the sameGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSameGroup() {
        return sameGroup;
    }

    /**
     * Sets the value of the sameGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSameGroup(String value) {
        this.sameGroup = value;
    }

    /**
     * Gets the value of the phoneIdA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneIdA() {
        return phoneIdA;
    }

    /**
     * Sets the value of the phoneIdA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneIdA(String value) {
        this.phoneIdA = value;
    }

    /**
     * Gets the value of the phoneIdB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneIdB() {
        return phoneIdB;
    }

    /**
     * Sets the value of the phoneIdB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneIdB(String value) {
        this.phoneIdB = value;
    }

}
